
CREATE DATABASE IF NOT EXISTS aquamind
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE aquamind;

CREATE TABLE IF NOT EXISTS Users (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(100) NOT NULL UNIQUE,
  Email VARCHAR(191) NOT NULL UNIQUE,
  PasswordHash VARCHAR(255) NOT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Tanks (
  TankID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Name VARCHAR(255) NOT NULL,
  VolumeLiters INT NULL,
  TankType VARCHAR(100) NULL,
  FishCount INT NOT NULL DEFAULT 0,
  PlantCount INT NOT NULL DEFAULT 0,
  FishNames TEXT NULL,
  PlantNames TEXT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WaterReadings (
  ReadingID INT AUTO_INCREMENT PRIMARY KEY,
  TankID INT NOT NULL,
  pH DECIMAL(4,2) NULL,
  Temperature DECIMAL(4,1) NULL,
  Ammonia DECIMAL(6,3) NULL,
  Nitrite DECIMAL(6,3) NULL,
  Nitrate DECIMAL(6,1) NULL,
  DissolvedO2 DECIMAL(4,1) NULL,
  RecordedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (TankID) REFERENCES Tanks(TankID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MaintenanceTasks (
  TaskID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  TankID INT NULL,
  TaskName VARCHAR(255) NOT NULL,
  DueDate DATE NOT NULL,
  DueTime VARCHAR(20) NULL,
  NotifiedAt DATETIME NULL,
  IsCompleted TINYINT(1) NOT NULL DEFAULT 0,
  CompletedAt DATETIME NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (TankID) REFERENCES Tanks(TankID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS MaintenanceLogs (
  LogID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  TankID INT NULL,
  TaskName VARCHAR(255) NOT NULL,
  DurationMinutes INT NULL,
  Notes TEXT NULL,
  CompletedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (TankID) REFERENCES Tanks(TankID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Alerts (
  AlertID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  TankID INT NULL,
  AlertType VARCHAR(50) NOT NULL,
  Title VARCHAR(255) NOT NULL,
  Detail TEXT NULL,
  IsRead TINYINT(1) NOT NULL DEFAULT 0,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (TankID) REFERENCES Tanks(TankID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS GrowthRecords (
  GrowthID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  TankID INT NOT NULL,
  FishName VARCHAR(255) NOT NULL,
  LengthCm DECIMAL(6,2) NOT NULL,
  WeightG DECIMAL(8,2) NULL,
  Notes TEXT NULL,
  RecordedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (TankID) REFERENCES Tanks(TankID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Equipment (
  EquipmentID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  TankID INT NULL,
  Name VARCHAR(255) NOT NULL,
  Type VARCHAR(50) NOT NULL,
  Brand VARCHAR(255) NULL,
  Status VARCHAR(50) NOT NULL DEFAULT 'Working',
  Notes TEXT NULL,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
  FOREIGN KEY (TankID) REFERENCES Tanks(TankID) ON DELETE SET NULL
);
