CREATE DATABASE AquaMindDB;
GO
USE AquaMindDB;
GO

CREATE TABLE Users (
  UserID INT PRIMARY KEY IDENTITY(1,1),
  Username NVARCHAR(50) NOT NULL UNIQUE,
  Email NVARCHAR(100) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE Tanks (
  TankID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
  Name NVARCHAR(100) NOT NULL,
  VolumeLiters INT NULL,
  TankType NVARCHAR(50) NULL,
  FishCount INT NOT NULL DEFAULT 0,
  PlantCount INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE WaterReadings (
  ReadingID INT PRIMARY KEY IDENTITY(1,1),
  TankID INT NOT NULL FOREIGN KEY REFERENCES Tanks(TankID) ON DELETE CASCADE,
  pH DECIMAL(4,2) NULL,
  Temperature DECIMAL(4,1) NULL,
  Ammonia DECIMAL(6,3) NULL,
  Nitrite DECIMAL(6,3) NULL,
  Nitrate DECIMAL(6,1) NULL,
  DissolvedO2 DECIMAL(4,1) NULL,
  RecordedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE MaintenanceTasks (
  TaskID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
  TankID INT NULL FOREIGN KEY REFERENCES Tanks(TankID) ON DELETE SET NULL,
  TaskName NVARCHAR(100) NOT NULL,
  DueDate DATE NOT NULL,
  DueTime NVARCHAR(20) NULL,
  IsCompleted BIT NOT NULL DEFAULT 0,
  CompletedAt DATETIME2 NULL,
  CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE MaintenanceLogs (
  LogID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
  TankID INT NULL FOREIGN KEY REFERENCES Tanks(TankID) ON DELETE SET NULL,
  TaskName NVARCHAR(100) NOT NULL,
  DurationMinutes INT NULL,
  Notes NVARCHAR(500) NULL,
  CompletedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE Alerts (
  AlertID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
  TankID INT NULL FOREIGN KEY REFERENCES Tanks(TankID) ON DELETE SET NULL,
  AlertType NVARCHAR(20) NOT NULL,
  Title NVARCHAR(100) NOT NULL,
  Detail NVARCHAR(255) NULL,
  IsRead BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE INDEX IX_Tanks_UserID ON Tanks(UserID);
CREATE INDEX IX_WaterReadings_TankID ON WaterReadings(TankID);
CREATE INDEX IX_MaintenanceTasks_UserID ON MaintenanceTasks(UserID);
CREATE INDEX IX_Alerts_UserID ON Alerts(UserID);
